apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: yt
spec:
  selector:
    app: yt-backend
  ports:
    - protocol: TCP
      port: 5000 
      targetPort: 5000 
  type: ClusterIP 
