apiVersion: v1
kind: Service
metadata:
  name: localhost:5000
  namespace: yt
spec:
  selector:
    app: yt-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
