name: Frontend & Backend CI/CD (Docker Hub)

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Generate random Docker tags
      - name: Generate Docker Tags
        run: |
          FRONTEND_TAG=v.$(shuf -i 10-99 -n 1)
          BACKEND_TAG=v.$(shuf -i 10-99 -n 1)
          echo "FRONTEND_TAG=$FRONTEND_TAG" >> $GITHUB_ENV
          echo "BACKEND_TAG=$BACKEND_TAG" >> $GITHUB_ENV
          echo "Frontend tag: $FRONTEND_TAG"
          echo "Backend tag: $BACKEND_TAG"

      # 4️⃣ Build & Push Frontend Image
      - name: Build & Push Frontend Image
        working-directory: frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/yt-frontend:${{ env.FRONTEND_TAG }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/yt-frontend:${{ env.FRONTEND_TAG }}

      # 5️⃣ Build & Push Backend Image
      - name: Build & Push Backend Image
        working-directory: backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/yt-backend:${{ env.BACKEND_TAG }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/yt-backend:${{ env.BACKEND_TAG }}
    