name: Frontend & Backend CI/CD (Docker Hub)

on:
  push:
    branches:
      - main

jobs:
  build-and-pushs:
    runs-on: ubuntu-latest
    outputs:
      frontend_tag: ${{ steps.set-tags.outputs.frontend }}
      backend_tag: ${{ steps.set-tags.outputs.backend }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Docker Tags
        id: set-tags
        run: |
          FRONTEND_TAG=v.$(shuf -i 10-99 -n 1)
          BACKEND_TAG=v.$(shuf -i 10-99 -n 1)
          echo "frontend=$FRONTEND_TAG" >> $GITHUB_OUTPUT
          echo "backend=$BACKEND_TAG" >> $GITHUB_OUTPUT
          echo "Frontend tag: $FRONTEND_TAG"
          echo "Backend tag: $BACKEND_TAG"

      - name: Build & Push Frontend Image
        working-directory: frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/yt-frontend:${{ steps.set-tags.outputs.frontend }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/yt-frontend:${{ steps.set-tags.outputs.frontend }}

      - name: Build & Push Backend Image
        working-directory: backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/yt-backend:${{ steps.set-tags.outputs.backend }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/yt-backend:${{ steps.set-tags.outputs.backend }}
